package com.mobdeve.s12.tiltosurvive;

public enum Keys {
    KEY_TV_BALANCE,
    KEY_TV_SCORE,
    KEY_TV_TIME,
    KEYS_IB_FIRST,
    KEYS_IB_SECOND,
    KEYS_IB_THIRD,
    KEYS_ACTIVATED_FIRST,
    KEYS_ACTIVATED_SECOND,
    KEYS_ACTIVATED_THIRD,
    KEYS_USED_FIRST,
    KEYS_USED_SECOND,
    KEYS_USED_THIRD,
    KEYS_INGAME_SIZE
}
